import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#406900",
        "primary-fixed": "#9ffb00",
        "primary-fixed-dim": "#8bdc00",
        "primary-container": "#a2ff00",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#102000",
        "on-primary-container": "#467200",
        background: "#1C1C1E",
        surface: "#2C2C2E",
        "surface-bright": "#3A3A3C",
        "surface-dim": "#1C1C1E",
        "surface-container": "#3A3A3C",
        "surface-container-low": "#2C2C2E",
        "surface-container-high": "#3A3A3C",
        "surface-container-highest": "#48484A",
        "surface-container-lowest": "#2C2C2E",
        "on-surface": "#F5F5F7",
        "on-surface-variant": "#98989D",
        "on-background": "#F5F5F7",
        "surface-variant": "#48484A",
        "graphite-base": "#1C1C1E",
        "graphite-card": "#2C2C2E",
        "graphite-border": "#3A3A3C",
        secondary: "#8E8E93",
        "secondary-container": "#48484A",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#F5F5F7",
        "secondary-fixed": "#48484A",
        "secondary-fixed-dim": "#636366",
        "on-secondary-fixed": "#F5F5F7",
        "on-secondary-fixed-variant": "#98989D",
        tertiary: "#8E8E93",
        "tertiary-container": "#636366",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#F5F5F7",
        "tertiary-fixed": "#636366",
        "tertiary-fixed-dim": "#48484A",
        "on-tertiary-fixed-variant": "#98989D",
        outline: "#636366",
        "outline-variant": "#48484A",
        inverse: {
          surface: "#F5F5F7",
          "on-surface": "#1C1C1E",
          primary: "#8bdc00",
        },
        error: "#FF453A",
        "error-container": "#5C1A1A",
        "on-error": "#ffffff",
        "on-error-container": "#FFB3AB",
        neon: {
          DEFAULT: "#9ffb00",
          hover: "#8bdc00",
        },
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
