import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#406900",
        "primary-fixed": "#9ffb00",
        "primary-fixed-dim": "#8bdc00",
        "primary-container": "#a2ff00",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#102000",
        "on-primary-container": "#467200",
        surface: "#f8faf5",
        "surface-bright": "#f8faf5",
        "surface-dim": "#d8dbd6",
        "surface-container": "#ecefea",
        "surface-container-low": "#f2f4ef",
        "surface-container-high": "#e7e9e4",
        "surface-container-highest": "#e1e3de",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1a",
        "on-surface-variant": "#414a34",
        "on-background": "#191c1a",
        "surface-variant": "#e1e3de",
        secondary: "#5d5e61",
        "secondary-container": "#e2e2e5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#636467",
        "secondary-fixed": "#e2e2e5",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary-fixed": "#1a1c1e",
        "on-secondary-fixed-variant": "#454749",
        tertiary: "#5d5f5f",
        "tertiary-container": "#e6e6e6",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#1a1c1c",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c6",
        "on-tertiary-fixed-variant": "#454747",
        outline: "#717b61",
        "outline-variant": "#c0caad",
        inverse: {
          surface: "#2e312e",
          "on-surface": "#eff1ec",
          primary: "#8bdc00",
        },
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        neon: {
          DEFAULT: "#9ffb00",
          hover: "#8bdc00",
        },
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
