import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#331200",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#261900",
        "surface-bright": "#fbf9f1",
        "on-primary-container": "#583600",
        "on-secondary-container": "#672c00",
        "tertiary": "#775a19",
        "on-surface-variant": "#4f4634",
        "primary-container": "#d59e55",
        "secondary-fixed": "#ffdbc9",
        "tertiary-fixed-dim": "#e9c176",
        "on-surface": "#1b1c17",
        "on-primary-fixed": "#2a1700",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#513900",
        "background": "#fbf9f1",
        "outline": "#817662",
        "tertiary-fixed": "#ffdea5",
        "on-secondary": "#ffffff",
        "outline-variant": "#d3c5ae",
        "primary-fixed-dim": "#f7bb70",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#643e00",
        "secondary-fixed-dim": "#ffb68d",
        "error-container": "#ffdad6",
        "primary": "#815512",
        "surface-container-high": "#eae8e0",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e3db",
        "inverse-on-surface": "#f3f1e9",
        "inverse-primary": "#f7bb70",
        "surface-tint": "#815512",
        "surface-dim": "#dcdad2",
        "on-secondary-fixed-variant": "#763300",
        "on-background": "#1b1c17",
        "surface-container-highest": "#e4e3db",
        "on-tertiary-fixed-variant": "#5d4201",
        "surface": "#fbf9f1",
        "secondary-container": "#fc8a40",
        "surface-container": "#f0eee6",
        "surface-container-low": "#f5f4ec",
        "secondary": "#9b4500",
        "tertiary-container": "#c8a35c",
        "inverse-surface": "#30312c",
        "primary-fixed": "#ffddb7",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        xl: "1.5rem",
      },
    },
  },
  plugins: [],
};
export default config;
